Refactor to main
lacework/terraform-lacework-alerts-to-aws-s3 pull request #4
Opened 2022-11-10 18:45 UTC by danifitz

## Summary

Fixes an issue where Terraform registry says this has no root. I refactored all diff files into a single `main.tf`

## How did you test this change?

n/a

2022-11-10 20:46 UTC, afiune requested changes
One thing to fix, then it is good to go.

As a side note, I don't think you needed to move "all" the code into the `main.tf`, but instead, Terraform was complaining that the file itself didn't exist. 😅

2022-11-10 20:46 UTC, afiune commented on README.md
> +| <a name="provider_lacework"></a> [lacework](#provider\_lacework) | ~> 0.20.0 |
can we bump this to be `~> 1.0`

2022-11-11 08:45 UTC, danifitz commented on README.md
> +| <a name="provider_lacework"></a> [lacework](#provider\_lacework) | ~> 0.20.0 |
Bumped!

2022-11-11 17:46 UTC, afiune approved these changes
We have three issues that, at some point, we need to resolve. @danifitz I am giving my +1 since this was a copy and paste but, this is why we need Pull Requests so that we notice these kinds of vulnerabilities and other things that run in CI.

Please, make sure to come back to this issues at your earliest convenient. Thanks

![tenor-69678117](https://user-images.githubusercontent.com/5712253/201399031-f4852733-7717-48a5-90bb-79f354522054.gif)

2022-11-11 17:47 UTC, merged